---
title: "UserGuide09"
header-includes:
   - \usepackage{bm}
   - \usepackage{amsmath,amssymb,mathrsfs,booktabs}
   - \newcommand{\matr}[1]{\mathbf{#1}} % undergraduate algebra version
author: "Silvan Hüsler"
date: "18 Januar 2017"
output: 
  pdf_document:
    toc: TRUE
    keep_tex: false
    highlight: pygments
    number_sections: false
nocite: | 
  @Hox.2014, @Zhang.2016
# -------------------------------------------------
references:
- id: Hox.2014
  type: chapter
  author:
  - family: Hox
    given: Joop
  - family: Wijngaards-de Meij
    given: Leoniek
  editor:
  - family: Best
    given: Henning
  - family: Wolf
    given: Christof
  issued:
  - year: '2014'
  title: The multilevel regression model
  container-title: The sage handbook of regression analysis and causal inference
  publisher: SAGE Publications Ltd
  page: '133-152'
  DOI: 10.4135/9781446288146.n7
  ISBN: '9781446252444'
# -------------------------------------------------
- id: Zhang.2016
  type: article-journal
  author:
  - family: Zhang
    given: Zhengzheng
  - family: Parker
    given: Richard M. A.
  - family: Charlton
    given: Christopher M. J.
  - family: Leckie
    given: George
  - family: Browne
    given: William J.
  issued:
  - year: '2016'
  title: 'R2MLwiN: A package to run mlwin from within r'
  title-short: R2MLwiN
  container-title: Journal of Statistical Software
  volume: '72'
  issue: '10'
  DOI: 10.18637/jss.v072.i10
  ISSN: '1548-7660'
# *+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=TRUE)
```


```{r pakete, include=FALSE}
library("tidyverse")
library("purrr")
library("lazyeval")
library("readr")
library("haven")
library("lubridate")
library("magrittr")
library("stringr")
library("tibble")
library("zoo")
library("dygraphs")
library("plotly")
library("glmmML")
library("survival")
library("forcats")
library("wesanderson")
library("car")
options(tibble.print_min = 100)
options(scipens = 9999999999999999999)
library("R2MLwiN")
library("doBy")
options(MLwiN_path = "C:/Program Files (x86)/MLwiN trial/i386/")
```




```{r}
data(bang, package = "R2MLwiN")
summary(bang)
```


```{r}
addmargins(with(bang, table(lc, use)))
```


## 9.3 A two-level random intercept model 


```{r}
(mymodel4 <- runMLwiN(
  logit(use) ~ 1 + lc + age + (1 | district), 
  D = "Binomial", 
  data = bang))
```


```{r}
(mymodel5 <- runMLwiN(
  logit(use) ~ 1 + lc + age + (1 | district), 
  D = "Binomial", 
  estoptions = list(
    nonlinear = c(N = 1,M = 2), 
    startval = list(
      FP.b = mymodel4@FP, 
      FP.v = mymodel4@FP.cov, 
      RP.b = mymodel4@RP, 
      RP.v = mymodel4@RP.cov)),
  data = bang))
```


```{r}
linearHypothesis(mymodel5, "RP2_var_Intercept = 0")
```


### Variance partition coeficient


$$
\frac{\text{exp}(x)}{1 + \text{exp}(x)}
$$


```{r}
set.seed(1)

invlogit <- function(x) exp(x)/(1 + exp(x))

u <- sqrt(coef(mymodel5)["RP2_var_Intercept"]) * qnorm(runif(5000))
str(u)

p1 <- invlogit(coef(mymodel5)["FP_Intercept"] + u)

p2 <- invlogit(coef(mymodel5)["FP_Intercept"] + 
                 coef(mymodel5)["FP_lcThree_plus"] + 
                 coef(mymodel5)["FP_age"] * -9.7 + u)

p3 <- invlogit(coef(mymodel5)["FP_Intercept"] + 
                 coef(mymodel5)["FP_age"] * 15.3 + u)

v1 <- p1 * (1 - p1)
lev2var1 <- sd(p1)^2
lev1var1 <- mean(v1)

v2 <- p2 * (1 - p2)
lev2var2 <- sd(p2)^2
lev1var2 <- mean(v2)

v3 <- p3 * (1 - p3)
lev2var3 <- sd(p3)^2
lev1var3 <- mean(v3)

cat(
  paste0("VPC = ", lev2var1/(lev2var1 + lev1var1)))

cat(
  paste0(
    "VPC for a young women with 3+ children (low probability use) = ", 
    na.omit(lev2var2/(lev2var2 + lev1var2))))

cat(
  paste0(
    "VPC for an old woman with no children (high probability use) = ", 
    lev2var3/(lev2var3 + lev1var3)))
```



## Literatur



